FROM golang:1.26-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd

FROM alpine:3.22.4

WORKDIR /app

EXPOSE 50051 8080

COPY --from=build /app/main .

COPY internal/infra/driven/persistence/sql ./internal/infra/driven/persistence/sql

ENTRYPOINT ["./main"]
