FROM golang:1.26-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd

FROM alpine:3.22.4

WORKDIR /root

COPY --from=build /app/main .

CMD ["./main"]
