#!/usr/bin/env bash
set -euo pipefail

# Creates a temporary .env in repo root for build/compose.yml (env_file: ../.env)

umask 077

cat >.env <<EOF
DB_USER=${DB_USER}
SQL_PASSWORD=${SQL_PASSWORD}
DB_PJ_NAME=${DB_PJ_NAME}
DB_PJ_PORT=${DB_PJ_PORT}
GRPC_ADDR=${GRPC_ADDR}
HEALTH_ADDR=${HEALTH_ADDR}
HEALTH_ENABLED=${HEALTH_ENABLED}
APP_ENV=${APP_ENV}
COMPOSE_RESTART_POLICY=${COMPOSE_RESTART_POLICY}
GRPC_REFLECTION_ENABLED=${GRPC_REFLECTION_ENABLED}
GOTOOLCHAIN=${GOTOOLCHAIN}
APP_PORT=${APP_PORT}
HEALTH_PORT=${HEALTH_PORT}
EOF

chmod 600 .env
