name: conventional_commits

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      base_sha:
        required: true
        type: string
      head_sha:
        required: true
        type: string

permissions:
  contents: read

jobs:
  commitlint:
    name: Commilint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24

      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: Validate commit messages
        run: |
          npx commitlint --config=config/.commitlintrc.json \
                        --from ${{ inputs.base_sha }} \
                        --to ${{ inputs.head_sha }} \
                        --verbose
