name: golangci_lint

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci_lint:
    name: Go linter
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/setup-checkout

      - uses: ./.github/actions/setup-go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee
        with:
          install-mode: goinstall
          args: --timeout=5m --config=config/.golangci.yml
